sensors:

  camera_intrinsics:
    diagonal_fov_deg: 120.0
    width: 320
    height: 240
    update_rate: 8
    near_clip: 0.1
    far_clip: 2000

  lidar_intrinsics:
    horizontal_samples: 240
    h_min_angle: -3.14159
    h_max_angle: 3.14159
    vertical_samples: 40
    v_min_angle: 0.12217
    v_max_angle: 0.90757
    min_range: 0.1
    max_range: 70.0
    range_resolution: 0.01
    update_rate: 4

aircraft_models:

  alti_transition_quad:
    camera_extrinsics: "0.85 0 -0.05 0 0 0"
    lidar_extrinsics: "0 0 -0.15 180 0 0"

  iris_with_ardupilot:
    camera_extrinsics: ".175 0 -0.075 0 0 0"
    lidar_extrinsics: "0 0 .08 0 0 0"

  standard_vtol:
    camera_extrinsics: ".525 0 0 0 0 0"
    lidar_extrinsics: "0 0 -0.08 180 0 0"

  x500:
    camera_extrinsics: ".175 0 -0.075 0 0 0"
    lidar_extrinsics: "0 0 .08 0 0 0"
