set -g mouse on
setw -g mode-keys vi
# Bind 'y' (yank, vi's copy) and MouseDragEnd (select and drag with the mouse to copy) to pipe to the X11 clipboard
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -i"
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -i"
